services:
  app:
    build: .
    container_name: TAIF-mail
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://taif-mail-ollama:11434
      - OCR_GPU=true
      - OCR_CUDA_DEVICE=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    volumes:
      - .:/app
    command: "python app.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:latest
    container_name: taif-mail-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

    environment:
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-pull-model:
    image: curlimages/curl:latest
    container_name: taif-mail-ollama-pull
    depends_on:
      - ollama
    restart: "no"
    entrypoint: [ "sh", "-c", "until curl -s http://ollama:11434/api/tags > /dev/null; do sleep 1; done; echo 'Starting model pull...'; curl -s -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen3:8b\"}' > /dev/null && echo 'Model pulled successfully!'" ]

volumes:
  ollama:
