services: 
  flask:
    build: .
    container_name: TAIF-mail
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    ports:
      - "8000:8000"  # публикуем порт
    command: gunicorn app:app -b 0.0.0.0:8000 -w 4  # слушаем все интерфейсы