services: 
  flask:
    build: .
    container_name: TAIF-mail
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: unless-stopped
    ports:
      - "8000:8000"  # публикуем порт
    command: gunicorn app:app -b 0.0.0.0:8000 -w 4  # слушаем все интерфейсы
    volumes:
      - .:/app:ro  # код, перезагружается при git pull
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: taif-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama  # модели сохраняются
    command: ollama run bambucha/saiga-llama3
    restart: unless-stopped