name: CI for AI agent

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Send to server
      run: scp -r . ai@10.100.40.215:/home/ai/taif-mail
      
    - name: Show date
      run: date