name: CI for AI agent

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: self-hosted

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install test dependencies
      run: |
        python3 -m pip install -r requirements-test.txt

    - name: Unit tests
      env:
        PYTHONPATH: .
      run: |
        python3 -m unittest discover -s tests -p "test_*.py" -v

    - name: Directum test
      env:
        PYTHONPATH: .
      run: |
        pytest --username=${{ secrets.LOGIN_NAME }} --password=${{ secrets.DIRECTUM_PASS }} --url=${{ secrets.ODATA_URL }} tests/directum_test.py

    - name: Email test
      env:
        PYTHONPATH: .
      run: |
        pytest --username=${{ secrets.LOGIN_NAME }} --password=${{ secrets.EMAIL_PASS }} tests/email_test.py

  deploy:
    runs-on: self-hosted
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      run: |
          ssh -o StrictHostKeyChecking=no ai@10.100.40.215 << 'EOF'
            cd /home/ai/taif-mail
            git pull origin main
          EOF
